name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[[routes]]
pattern = "blazenote-backend.feisty-quasar.sxplab.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "b35c390e-b0d0-4d8e-9f49-09b18fe1a138"
migrations_dir = "./migrations"

# [ai]
# binding = "AI"

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "blazenote"
# preview_bucket_name = "dev-blazenote"

[observability.logs]
enabled = true